import Head from "next/head";
import Image from "next/image";

import Map, { Marker } from "react-map-gl";
import "mapbox-gl/dist/mapbox-gl.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Muck Spot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-xl">
          Welcome to <a href="https://nextjs.org" className="text-3xl underline to-blue-500">Muck Spot!</a>
        </h1>

        <Map
          style={{ width: "100vw", height: "100vh" }}
          mapStyle={process.env.NEXT_PUBLIC_MAPBOX_STYLE}
          mapboxAccessToken={process.env.NEXT_PUBLIC_MAPBOX_KEY}
          ititialViewState={{
            longitude: -122.4,
            latitude: 37.8,
            zoom: 14,
          }}
        />

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
